package com.labsync.lms.model;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDateTime;
import java.time.LocalTime;

/**
 * Schedule entity — the central timetable record.
 * Links batch, subject, staff, lab, and day with start/end time.
 */
@Entity
@Table(name = "schedules")
public class Schedule {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "batch_id", nullable = false)
    private Batch batch;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "subject_id", nullable = false)
    private Subject subject;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "staff_id", nullable = false)
    private Staff staff;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lab_id", nullable = false)
    private Lab lab;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "day_id", nullable = false)
    private Day day;
    @Column(nullable = false)
    private LocalTime startTime;
    @Column(nullable = false)
    private LocalTime endTime;
    /**
     * Marks if schedule was generated by the Genetic Algorithm
     */
    @Column(nullable = false)
    private boolean generatedByGA;
    /**
     * Reference to which GA run produced this schedule
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "algorithm_run_id")
    private AlgorithmRun algorithmRun;
    @Column(nullable = false)
    private boolean active;
    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;

    private static boolean $default$generatedByGA() {
        return false;
    }

    private static boolean $default$active() {
        return true;
    }


    public static class ScheduleBuilder {
        private Long id;
        private Batch batch;
        private Subject subject;
        private Staff staff;
        private Lab lab;
        private Day day;
        private LocalTime startTime;
        private LocalTime endTime;
        private boolean generatedByGA$set;
        private boolean generatedByGA$value;
        private AlgorithmRun algorithmRun;
        private boolean active$set;
        private boolean active$value;
        private LocalDateTime createdAt;

        ScheduleBuilder() {
        }

        /**
         * @return {@code this}.
         */
        public Schedule.ScheduleBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Schedule.ScheduleBuilder batch(final Batch batch) {
            this.batch = batch;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Schedule.ScheduleBuilder subject(final Subject subject) {
            this.subject = subject;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Schedule.ScheduleBuilder staff(final Staff staff) {
            this.staff = staff;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Schedule.ScheduleBuilder lab(final Lab lab) {
            this.lab = lab;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Schedule.ScheduleBuilder day(final Day day) {
            this.day = day;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Schedule.ScheduleBuilder startTime(final LocalTime startTime) {
            this.startTime = startTime;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Schedule.ScheduleBuilder endTime(final LocalTime endTime) {
            this.endTime = endTime;
            return this;
        }

        /**
         * Marks if schedule was generated by the Genetic Algorithm
         * @return {@code this}.
         */
        public Schedule.ScheduleBuilder generatedByGA(final boolean generatedByGA) {
            this.generatedByGA$value = generatedByGA;
            generatedByGA$set = true;
            return this;
        }

        /**
         * Reference to which GA run produced this schedule
         * @return {@code this}.
         */
        public Schedule.ScheduleBuilder algorithmRun(final AlgorithmRun algorithmRun) {
            this.algorithmRun = algorithmRun;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Schedule.ScheduleBuilder active(final boolean active) {
            this.active$value = active;
            active$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        public Schedule.ScheduleBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        public Schedule build() {
            boolean generatedByGA$value = this.generatedByGA$value;
            if (!this.generatedByGA$set) generatedByGA$value = Schedule.$default$generatedByGA();
            boolean active$value = this.active$value;
            if (!this.active$set) active$value = Schedule.$default$active();
            return new Schedule(this.id, this.batch, this.subject, this.staff, this.lab, this.day, this.startTime, this.endTime, generatedByGA$value, this.algorithmRun, active$value, this.createdAt);
        }

        @java.lang.Override
        public java.lang.String toString() {
            return "Schedule.ScheduleBuilder(id=" + this.id + ", batch=" + this.batch + ", subject=" + this.subject + ", staff=" + this.staff + ", lab=" + this.lab + ", day=" + this.day + ", startTime=" + this.startTime + ", endTime=" + this.endTime + ", generatedByGA$value=" + this.generatedByGA$value + ", algorithmRun=" + this.algorithmRun + ", active$value=" + this.active$value + ", createdAt=" + this.createdAt + ")";
        }
    }

    public static Schedule.ScheduleBuilder builder() {
        return new Schedule.ScheduleBuilder();
    }

    public Long getId() {
        return this.id;
    }

    public Batch getBatch() {
        return this.batch;
    }

    public Subject getSubject() {
        return this.subject;
    }

    public Staff getStaff() {
        return this.staff;
    }

    public Lab getLab() {
        return this.lab;
    }

    public Day getDay() {
        return this.day;
    }

    public LocalTime getStartTime() {
        return this.startTime;
    }

    public LocalTime getEndTime() {
        return this.endTime;
    }

    /**
     * Marks if schedule was generated by the Genetic Algorithm
     */
    public boolean isGeneratedByGA() {
        return this.generatedByGA;
    }

    /**
     * Reference to which GA run produced this schedule
     */
    public AlgorithmRun getAlgorithmRun() {
        return this.algorithmRun;
    }

    public boolean isActive() {
        return this.active;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    public void setBatch(final Batch batch) {
        this.batch = batch;
    }

    public void setSubject(final Subject subject) {
        this.subject = subject;
    }

    public void setStaff(final Staff staff) {
        this.staff = staff;
    }

    public void setLab(final Lab lab) {
        this.lab = lab;
    }

    public void setDay(final Day day) {
        this.day = day;
    }

    public void setStartTime(final LocalTime startTime) {
        this.startTime = startTime;
    }

    public void setEndTime(final LocalTime endTime) {
        this.endTime = endTime;
    }

    /**
     * Marks if schedule was generated by the Genetic Algorithm
     */
    public void setGeneratedByGA(final boolean generatedByGA) {
        this.generatedByGA = generatedByGA;
    }

    /**
     * Reference to which GA run produced this schedule
     */
    public void setAlgorithmRun(final AlgorithmRun algorithmRun) {
        this.algorithmRun = algorithmRun;
    }

    public void setActive(final boolean active) {
        this.active = active;
    }

    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public Schedule() {
        this.generatedByGA = Schedule.$default$generatedByGA();
        this.active = Schedule.$default$active();
    }

    /**
     * Creates a new {@code Schedule} instance.
     *
     * @param id
     * @param batch
     * @param subject
     * @param staff
     * @param lab
     * @param day
     * @param startTime
     * @param endTime
     * @param generatedByGA Marks if schedule was generated by the Genetic Algorithm
     * @param algorithmRun Reference to which GA run produced this schedule
     * @param active
     * @param createdAt
     */
    public Schedule(final Long id, final Batch batch, final Subject subject, final Staff staff, final Lab lab, final Day day, final LocalTime startTime, final LocalTime endTime, final boolean generatedByGA, final AlgorithmRun algorithmRun, final boolean active, final LocalDateTime createdAt) {
        this.id = id;
        this.batch = batch;
        this.subject = subject;
        this.staff = staff;
        this.lab = lab;
        this.day = day;
        this.startTime = startTime;
        this.endTime = endTime;
        this.generatedByGA = generatedByGA;
        this.algorithmRun = algorithmRun;
        this.active = active;
        this.createdAt = createdAt;
    }
}
